version: "3"
services:
  client:
    image: "martstech/revelled-client"
    mem_limit: 128m
    hostname: client
  api:
    image: "martstech/revelled-api"
    mem_limit: 128m
    hostname: api
    environment:
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_HOST=$MYSQL_HOST
      - MYSQL_PORT=$MYSQL_PORT
      - MYSQL_DATABASE=$MYSQL_DATABASE
  nginx:
    image: "martstech/revelled-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
