version: "3"
services:
  client:
    build:
      context: ./packages/client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  api:
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    ports:
      - "8000:80"
