version: "3"
services:
  mysql:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./packages/nginx
    ports:
      - "3000:80"
    depends_on:
      - api
      - client
  api:
    build:
      dockerfile: Dockerfile
      context: ./packages/api
    environment:
      - CHOKIDAR_USEPOLLING=true
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=root
    depends_on:
      - mysql
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./packages/client
    volumes:
      - /app/node_modules
      - ./packages/client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
