version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  api:
    build:
      dockerfile: Dockerfile
      context: ./packages/api
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=postgres_password
      - PG_PORT=5432
    ports:
      - "8000:80"
    depends_on:
      - postgres
  client:
    stdin_open: true
    build:
      context: ./packages/client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./packages/client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
