// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Events.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("EventId");

                    b.ToTable("Event", (string)null);

                    b.HasData(
                        new
                        {
                            EventId = new Guid("5bfabe3a-ef6e-497d-9b2d-664d7f9f19c3"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2022, 2, 5, 17, 34, 4, 432, DateTimeKind.Local).AddTicks(7517),
                            Description = "Event 2 months ago",
                            Title = "Past Event 1",
                            Venue = "Pub"
                        },
                        new
                        {
                            EventId = new Guid("cb99fa2e-3216-40eb-b0a0-99c05db1db0c"),
                            Category = "culture",
                            City = "Paris",
                            Date = new DateTime(2022, 3, 5, 17, 34, 4, 432, DateTimeKind.Local).AddTicks(7555),
                            Description = "Event 1 month ago",
                            Title = "Past Event 2",
                            Venue = "Louvre"
                        },
                        new
                        {
                            EventId = new Guid("f2b25220-03b7-4fdb-8ddb-aaef7f0fbf9a"),
                            Category = "culture",
                            City = "London",
                            Date = new DateTime(2022, 5, 5, 17, 34, 4, 432, DateTimeKind.Local).AddTicks(7560),
                            Description = "Event 1 month in the future",
                            Title = "Future Event 1",
                            Venue = "Natural History Museum"
                        },
                        new
                        {
                            EventId = new Guid("535b0387-c330-49df-8317-c2b304d1ee60"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2022, 6, 5, 17, 34, 4, 432, DateTimeKind.Local).AddTicks(7563),
                            Description = "Event 2 months in the future",
                            Title = "Future Event 2",
                            Venue = "02 Arena"
                        },
                        new
                        {
                            EventId = new Guid("f5f20ef4-54a0-46f0-8bb6-121255ff9d09"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2022, 7, 5, 17, 34, 4, 432, DateTimeKind.Local).AddTicks(7567),
                            Description = "Event 3 months in the future",
                            Title = "Future Event 3",
                            Venue = "Another pub"
                        },
                        new
                        {
                            EventId = new Guid("1e7d64d4-c5b1-4f8a-aca4-8f0438d5a1f6"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2022, 8, 5, 17, 34, 4, 432, DateTimeKind.Local).AddTicks(7571),
                            Description = "Event 4 months in the future",
                            Title = "Future Event 4",
                            Venue = "Yet another pub"
                        },
                        new
                        {
                            EventId = new Guid("bfeeb167-7fd0-4425-9d9a-17b75960a7f2"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2022, 9, 5, 17, 34, 4, 432, DateTimeKind.Local).AddTicks(7575),
                            Description = "Event 5 months in the future",
                            Title = "Future Event 5",
                            Venue = "Just another pub"
                        },
                        new
                        {
                            EventId = new Guid("6fc1b26a-84a1-4588-9894-a9ad4ddba2da"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2022, 10, 5, 17, 34, 4, 432, DateTimeKind.Local).AddTicks(7578),
                            Description = "Event 6 months in the future",
                            Title = "Future Event 6",
                            Venue = "Roundhouse Camden"
                        },
                        new
                        {
                            EventId = new Guid("94ab1324-0c42-4046-a985-82c95dce37b8"),
                            Category = "travel",
                            City = "London",
                            Date = new DateTime(2022, 11, 5, 17, 34, 4, 432, DateTimeKind.Local).AddTicks(7587),
                            Description = "Event 7 months in the future",
                            Title = "Future Event 7",
                            Venue = "Somewhere on the Thames"
                        },
                        new
                        {
                            EventId = new Guid("92a26a4e-461a-47a8-b585-51b2e998bb75"),
                            Category = "film",
                            City = "London",
                            Date = new DateTime(2022, 12, 5, 17, 34, 4, 432, DateTimeKind.Local).AddTicks(7591),
                            Description = "Event 8 months in the future",
                            Title = "Future Event 8",
                            Venue = "Cinema"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
